### ISSUE TITLE
Presets should be added to iter

### ISSUE THREAD

**Issue by okeribok** [op1hacks/op1repacker#17]
After modifying with options "iter filter iter-gfx-lab", repacking and updating, I do not see the Iter synth in the preset list. I expect it to be between FM and PHASE. I do see the filter FX. Am I missing something?

**Comment by vifino** [comment]
Same here, downloaded the latest build from TE's site today.

**Comment by richrd** [comment]
Hi! Maybe that should be clarified a little in the readme. It doesn't show up in the presets list because this tool doesn't yet add any iter presets. To use it you need to press SHIFT+T1 in synth mode, and select the iter engine from there. When I get enough good iter presets from the community I'll add the presets to the tool. Feel free to send any nice patches you come up with and I'll include them!

**Comment by vifino** [comment]
Hi! Thank you for your reply.

You're obviously correct, iter is unlocked! I've messed with it for some time. Here's something I messed with: https://my.mixtape.moe/quahfm.aif
