### ISSUE TITLE
Lost USB Connectivity with Repacked 242

### ISSUE THREAD

**Issue by copb** [op1hacks/op1repacker#34]
Hey team,

Seems like I've lost USB connectivity with repacking firmware 242. I've used the repacker tool with no problems for over a year now, yet for some reason this time around this happened. I've tried different cables as well as different devices to connect it to, to no avail. I understand that the risk was on me, but just wanted to let you know in case you've seen it happen before or have any advice. No worries if not. Thanks.

**Comment by turbo** [comment]
(FWIW it's working fine for me)

**Comment by richrd** [comment]
Sorry to hear you have issues. I haven't heard of that before. Which mods did you use (although none of them should affect usb)? It's probably more likely that the usb port has gotten worn out somehow or clogged with dust. You could try to clean it and see if that helps.

**Comment by DurtiCurti** [comment]
Not sure if the OP responded on this one, but i’m going to repack with all mods enabled this evening on an original OP-1. I’ll update if any issues

**Comment by richrd** [comment]
He responded on the op-forum but it's still unclear what the cause of the problem was. I'm also running latest FW with all mods without any issues. Everything works just like before including the USB connection. I'm pretty sure the cause is unrelated to custom FW but I'll keep this issue open for now for any future follow ups.

**Comment by DurtiCurti** [comment]
Right on. I’ll give it a read through. Also no issues on my end with custom 242 FW
